/* Edit this file to add activities. Keep Japanese and English equally complete. */
const portfolio = {
  timeline: [
    {period:"Early Exploration",title:{ja:"幅広い学びへの関心",en:"Early exploration across fields"},text:{ja:"科学、教育、表現、社会活動を横断して、自分の問いを探してきた。",en:"Explored science, education, expression, and social action while looking for personal questions."}},
    {period:"Scientific Exploration",title:{ja:"科学の甲子園ジュニア・実験活動",en:"Science competitions and experimentation"},text:{ja:"科学の甲子園ジュニアや科学実験班を通じ、科学をチームで考え、試す経験を積んだ。",en:"Built experience thinking about and testing science collaboratively through science competitions and an experimental science group."}},
    {period:"Research",title:{ja:"大気科学と異常巻きアンモナイト",en:"Atmospheric science and heteromorphic ammonites"},text:{ja:"環境・大気の粒子と、古生物の形態・流体力学を、実験・文献・モデル化で探究している。",en:"Investigating atmospheric particles and the morphology and fluid dynamics of paleobiology through experiments, literature, and modeling."}},
    {period:"Education & Social Impact",title:{ja:"i-vent と教育プロジェクト",en:"i-vent and education projects"},text:{ja:"学生主体の活動を運営し、学びが自発的なものになる条件を考えている。",en:"Organizing student-led work and considering conditions that make learning self-directed."}},
    {period:"Entrepreneurship",title:{ja:"Startup Weekend Sapporo",en:"Startup Weekend Sapporo"},text:{ja:"課題発見から検証、プロトタイプ、発表までを短期間で実践した。",en:"Practiced problem finding, validation, prototyping, and presentation in a short cycle."}},
    {period:"Current",title:{ja:"IB DP と学際的な探究",en:"IB DP and interdisciplinary inquiry"},text:{ja:"IB Diploma Programmeで学びながら、科学・教育・起業を接続する次の問いを探究している。",en:"Studying in the IB Diploma Programme while pursuing the next questions connecting science, education, and entrepreneurship."}}
  ],
  research: [
    {meta:"SSP+ / Environmental & Atmospheric Science",title:{ja:"大気中の超微小粒子（UFP）",en:"Ultrafine particles in the atmosphere"},text:{ja:"酸性雨を出発点に、UFP、PM2.5、PM0.1へ関心を広げている。大学教員との研究経験とJpGU 2025への参加を通じ、実験・文献調査・モデル化を組み合わせて探究している。",en:"Starting with acid rain, I expanded my interest to UFPs, PM2.5, and PM0.1. Through research experience with a university professor and participation in JpGU 2025, I combine experiments, literature review, and modeling."},tags:["UFP","PM2.5","PM0.1","Aerosol physics","JpGU 2025"]},
    {meta:"Paleobiology × Physics",title:{ja:"異常巻きアンモナイトの遊泳",en:"Swimming in heteromorphic ammonites"},text:{ja:"3Dモデル（STL）と3Dプリントを用い、特異な殻形態が遊泳行動へ与えた影響を考察する。問いは「異常巻きアンモナイトの殻形態は、遊泳にどのように影響したのか」。",en:"Using 3D models (STL) and 3D printing, I examine how unusual shell morphology might have affected swimming. The question is: “How might the unusual shell morphology of heteromorphic ammonites have affected their swimming behavior?”"},tags:["Fluid dynamics","Buoyancy","Drag","3D modeling","Shell morphology"]},
    {meta:"Related inquiry",title:{ja:"物理 × 化学 × 環境問題",en:"Physics × Chemistry × environmental problems"},text:{ja:"大気粒子、気体、電気伝導、反応速度、熱、エネルギーをつなげ、環境問題を自然科学の複数の視点から理解することに関心がある。",en:"I am interested in understanding environmental problems from multiple scientific perspectives by connecting atmospheric particles, gases, electrical conductivity, reaction rates, heat, and energy."},tags:["Physics","Chemistry","Environmental science"]}
  ],
  impact: [
    {meta:"Student-led organization",title:{ja:"i-vent",en:"i-vent"},text:{ja:"中高生主体の教育・社会活動団体。理事会副会長／執行代表として、RealGeoGuesser、学生主体イベント、教育活動、組織運営に関わった。活動をNPO法人として展開する段階にも進めた。",en:"A student-led education and social-impact organization. As Vice Chair of the Board / Executive Representative, I worked on RealGeoGuesser, student-led events, educational activities, and organizational management, including progress toward operating as an NPO."},tags:["Leadership","RealGeoGuesser","Education","Organization"]},
    {meta:"Education project",title:{ja:"Playful School",en:"Playful School"},text:{ja:"教育をもっと楽しく、自分から参加したくなるものにするための活動。中心にある問いは「学びは、どうすれば生徒が心からやりたいと思うものになるか」。",en:"A project seeking to make education more enjoyable and genuinely inviting. Its core question is: “How can learning become something students genuinely want to do?”"},tags:["Learning science","Student agency","Education"]},
    {meta:"Concept stage",status:"[To be updated]",title:{ja:"S-Tent",en:"S-Tent"},text:{ja:"小学生向けの教育支援を目的とした学生団体の構想。実施済みの活動ではなく、構想段階のプロジェクトとして位置づけている。",en:"A student-organization concept intended to support elementary-school education. It is presented as a concept-stage project, not as completed activity."},tags:["Education","Concept stage"]}
  ],
  technology: [
    {meta:"Startup Weekend Sapporo",title:{ja:"短期間での仮説検証",en:"Rapid hypothesis validation"},text:{ja:"Startup Weekend SapporoでWinner／MVPを受賞。課題発見、仮説、検証、反復、プロトタイプ、プレゼンテーションを短期間で実践した。",en:"Won Winner / MVP at Startup Weekend Sapporo. Practiced problem discovery, hypotheses, validation, iteration, prototyping, and presentation in a short cycle."},tags:["Problem → Hypothesis → Validation → Iteration","Prototyping"]},
    {meta:"Technology",title:{ja:"学びを支援するアプリケーション",en:"Applications that support learning"},text:{ja:"Web／モバイルアプリを通じて教育や学習を支援することに関心がある。学習管理、学習最適化、co-mitなどのプロジェクトを今後も追加できる。",en:"I am interested in supporting education and learning through web and mobile applications. Future entries can include learning management, learning optimization, and co-mit."},tags:["HTML","CSS","JavaScript","TypeScript","React","React Native","Node.js","Firebase"]},
    {meta:"Current project schema",status:"[Add details]",title:{ja:"進行中プロジェクトの記録",en:"Current project record"},text:{ja:"新しいプロジェクトには、Title、Period、Role、Status、Description、Question、Approach、Outcome、What I Learned、Related Fields、Links、Imagesを追加する。",en:"For each new project, add Title, Period, Role, Status, Description, Question, Approach, Outcome, What I Learned, Related Fields, Links, and Images."},tags:["Editable","Data-driven"]}
  ],
  academic: [
    {meta:"IB Diploma Programme",title:{ja:"IB DP の学び",en:"IB DP studies"},text:{ja:"Japanese A SL、English B HL、Chemistry HL、Physics SL、Mathematics AA HL、History SLを履修。MYPでは主に6〜7を維持し、科目によって8を取得した。",en:"Studying Japanese A SL, English B HL, Chemistry HL, Physics SL, Mathematics AA HL, and History SL. In the MYP, I generally maintained 6–7 and achieved 8 in some subjects."},tags:["IB DP","Japanese A SL","English B HL","Chemistry HL","Physics SL","Math AA HL","History SL"]},
    {meta:"Mathematics",title:{ja:"Math AA HL と数理モデル",en:"Math AA HL and mathematical models"},text:{ja:"Functions、Probability & Statistics、Calculus、Mathematical modelling、高度な数学に関心がある。IB Mathematics AA HLと日本の数学教育を比較し、青チャート、赤チャート、一対一対応の演習、Haese Mathematicsも活用している。",en:"Interested in functions, probability and statistics, calculus, mathematical modelling, and higher-level mathematics. I compare IB Mathematics AA HL with Japanese mathematics education and use Ao Chart, Aka Chart, One-to-One Correspondence Exercises, and Haese Mathematics."},tags:["Functions","Statistics","Calculus","Modelling"]},
    {meta:"English & global learning",title:{ja:"国際的な学びのための英語",en:"English for international learning"},text:{ja:"英検2級・準1級を取得し、準1級スコアは2390。IELTSとTOEFLも学習しており、TOEFL iBT 110を目標にしている。英語を研究・学習・コミュニケーションのための道具として位置づけている。",en:"Earned EIKEN Grade 2 and Pre-1, with a Pre-1 score of 2390. I am also studying for IELTS and TOEFL, with a TOEFL iBT goal of 110. I see English as a tool for international research, learning, and communication."},tags:["EIKEN Pre-1","2390","IELTS","TOEFL iBT 110 goal"]}
  ],
  programs: [
    {meta:"Science competitions",title:{ja:"科学の甲子園ジュニア・科学活動",en:"Science competitions and activities"},text:{ja:"科学の甲子園ジュニア2022では札幌市内1位・最終予選、2023では一次予選通過・最終予選。JJMO、科学実験班、統計グラフ全国コンクール応募も含む。",en:"Science Olympiad Junior: 1st in Sapporo and final qualifying round in 2022; passed the first qualifying round and reached the final qualifying round in 2023. Also includes JJMO, an experimental science group, and an entry to the National Statistical Graph Competition."},tags:["Science Olympiad Junior 2022","2023","JJMO","Statistics"]},
    {meta:"Programs",status:"[Status to be confirmed]",title:{ja:"コンテスト・プログラム",en:"Competitions & programs"},text:{ja:"EF Speech Contest、EzoFrogs、MONO-COTO INNOVATION、全国高校生エッセイコンテスト、異能vation、My Project Award。各項目の参加・応募・選考通過・受賞の状況は、証明に基づき更新する。",en:"EF Speech Contest, EzoFrogs, MONO-COTO INNOVATION, National High School Essay Contest, Inno-vation, and My Project Award. Update each entry as Participant, Applicant, Selected, or Awarded based on evidence."},tags:["Participant / Applicant / Selected / Awarded"]},
    {meta:"Arts & communication",title:{ja:"演劇とTEDx編集活動",en:"Drama and TEDx editorial work"},text:{ja:"演劇部、中文連演劇大会2022・2024（2024年は優秀賞）を通じ、Communication、Teamwork、Expression、Audience awarenessを学んだ。TEDx関連の編集活動では、他者の考えを編集し伝えることにも関心を広げた。",en:"Through the drama club and the Chubunren Drama Competition in 2022 and 2024 (Excellence Award in 2024), I learned communication, teamwork, expression, and audience awareness. TEDx-related editorial work extended my interest to shaping and communicating other people’s ideas."},tags:["Drama","TEDx","Communication","Expression"]},
    {meta:"SSH field observation",title:{ja:"札幌を地学的に見る",en:"Seeing Sapporo geologically"},text:{ja:"学校のSSH活動の一つとして地学野外観察に参加。札幌という身近な都市を地学的に見る経験が、地学への興味につながった。",en:"Participated in geological field observation as part of the school’s SSH activities. Seeing the familiar city of Sapporo through geology strengthened my interest in Earth science."},tags:["SSH","Geology","Field observation"]}
  ],
  awards: [
    {title:{ja:"Startup Weekend Sapporo",en:"Startup Weekend Sapporo"},detail:{ja:"Winner / MVP",en:"Winner / MVP"}},
    {title:{ja:"Volunteer Spirit Award",en:"Volunteer Spirit Award"},detail:{ja:"National Prize",en:"National Prize"}},
    {title:{ja:"中文連演劇大会 2024",en:"Chubunren Drama Competition 2024"},detail:{ja:"優秀賞",en:"Excellence Award"}},
    {title:{ja:"科学の甲子園ジュニア 2022",en:"Science Olympiad Junior 2022"},detail:{ja:"札幌市内1位",en:"1st in Sapporo"}}
  ],
  learning: [
    {no:"01",title:{ja:"Curiosity",en:"Curiosity"},text:{ja:"「面白そう」を起点にする。",en:"Begin with what feels interesting."}},
    {no:"02",title:{ja:"Connection",en:"Connection"},text:{ja:"異なる分野をつなぐ。",en:"Connect different fields."}},
    {no:"03",title:{ja:"Experimentation",en:"Experimentation"},text:{ja:"考えるだけではなく試す。",en:"Do not only think; test."}},
    {no:"04",title:{ja:"Collaboration",en:"Collaboration"},text:{ja:"一人ではできないことをチームで実現する。",en:"Make possible with a team what cannot be done alone."}},
    {no:"05",title:{ja:"Reflection",en:"Reflection"},text:{ja:"活動後に、何がうまくいかなかったかを考える。",en:"After acting, consider what did not work."}},
    {no:"06",title:{ja:"Creation",en:"Creation"},text:{ja:"最終的には、自分自身で新しいものを作る。",en:"Ultimately, create something new yourself."}}
  ]
};
